##**NumPy Array**

O Array NumPy é um tipo de dado criado para executar rapidamente várias operações matemáticas. Lembre-se que Python é também orientado a objetos, NumPy é uma classe, portanto contém atributos e métodos. O objeto desta classe é o Array (um vetor).

Quando pensamos na forma "usual" de descrever um vetor podemos pensar que basta somar os números entre [ ] para formar um vetor. Porém, assim construímos apenas listas em Python, e não arrays!

In [ ]:
# Criando listas
linha1 = [7, 6, 5, 4]
linha2 = [3, 2, 1, 0]

# Transformando em uma matriz
A = []
A += [linha1]
A += [linha2]

print (A)

[[7, 6, 5, 4], [3, 2, 1, 0]]


Acabamos de criar uma matriz com duas linhas e quatro colunas. Podemos acessar os elementos do array através da sintaxe A[i][j]:

In [ ]:
print (f"A(0,3) = {A[0][3]}")

print (f"A(1,1) = {A[1][1]}")

A(0,3) = 4
A(1,1) = 2


Exemplo: Agora tente escrever uma função que receba como argumento o número de linhas `n_linhas` e colunas `n_cols` de uma matriz e um determinado valor `k`, e retorne uma matriz `n_lines` x `n_cols` preenchida com o valor `k`. Em seguida, imprima a matriz produzida.




In [ ]:
def gera_matriz(n_linhas, n_cols, k):
  A = []
  for i in range(n_linhas):
    linha = []
    for j in range(n_cols):
      linha += [k]
    A += [linha]
  return A

def imprime_matriz(A):
  n_linhas = len(A)
  n_cols = len(A[0])
  for i in range(n_linhas):
    for j in range(n_cols):
      print (f"{A[i][j]:.3f}", end=' ')
    print()

M = gera_matriz(4, 6, 5.5)
imprime_matriz(M)

5.500 5.500 5.500 5.500 5.500 5.500 
5.500 5.500 5.500 5.500 5.500 5.500 
5.500 5.500 5.500 5.500 5.500 5.500 
5.500 5.500 5.500 5.500 5.500 5.500 


E se precisarmos dobrar o valor de uma matriz?

In [ ]:
print([2, 5, 10] * 2)
print([2, 5, 10] + [2, 5, 10])

[2, 5, 10, 2, 5, 10]
[2, 5, 10, 2, 5, 10]


Você poderia novamente usar um for, ou while. Mas não seria uma solução direta.

Além disso, temos o problema com o "len" (tamanho):

In [ ]:
notas = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(len(notas))

3


Por quê isso acontece?
Temos 3 listas, não sabemos diretamente o número de elementos em cada lista.

Além de resolver esses problemas, o array usa menos memória do que a lista, é mais rápido nas operações de leitura e possibilita executar operações matemáticas sobre todos os itens de uma só vez. Como ponto negativo, no array todos os elementos **têm que ter o mesmo tipo de dado**, mas a lista pode ter elementos de tipos diferentes.

Para declarar um array, é preciso importar o módulo numpy e declarar os seus arrays simples.

In [ ]:
import numpy as np
matriz1d = np.array([1, 2, 3])
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Criação muito mais direta para matrizes (para vetores, nem tanto).

Como fazemos para resolver o problema da duplicação de uma matriz usando o NumPy?

In [ ]:
print(matriz1d * 2)
print(matriz1d + matriz1d)

[2 4 6]
[2 4 6]


Aqui podemos ver que as operações funcionam como esperamos da matemática.

In [ ]:
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2d2 = np.array([[20, 12, 10], [16, 55, 45], [33, 27, 18]])
print(matriz2d + matriz2d2)
print(matriz2d2 - matriz2d)
print(matriz2d*2)

[[21 14 13]
 [20 60 51]
 [40 35 27]]
[[19 10  7]
 [12 50 39]
 [26 19  9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Para analisarmos o tamanho de uma matriz, agora usamos o atributo shape, que é uma tupla (lista imutável) que contém as informações de quantos elementos são armazenados em cada dimensão de um array.

In [ ]:
print(matriz2d.shape)

(3, 3)


Também podemos verificar a dimensão das matrizes:

In [ ]:
matriz1d = np.array([1, 2, 3])

matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(matriz1d.ndim)
print(matriz2d.ndim)
print(matriz3d.ndim)

1
2
3


**Multiplicação de matrizes** é algo a ser lembrado. Seja A uma matriz m x n e B uma matriz n x p, a multiplicação de A e B é uma matriz C de dimensões m x p. Geralmente, A\*B ≠ B\*A. A multiplicação de matrizes em NumPy é utilizando o método dot.

In [ ]:
print(np.dot(matriz2d, matriz2d2))
print(np.dot(matriz2d2, matriz2d))
matriz23 = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz23.shape)
print(np.dot(matriz23, matriz2d))
print(np.dot(matriz2d, matriz23))

[[151 203 154]
 [358 485 373]
 [565 767 592]]
[[138 180 222]
 [551 667 783]
 [267 345 423]]
(2, 3)
[[30 36 42]
 [66 81 96]]


ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Veja que temos A*B ≠ de B*A!

Por que tivemos o erro na última tentativa?

O operador * não é utilizado para multiplicação de matrizes! Ele serve para propagar arrays menores em maiores.

Alguns métodos específicos para criação de matrizes merecem ser mencionados:

In [ ]:
print(np.zeros((1, 3)))
print(np.ones((2, 2)))
print(np.full((1, 2), 3.0))

[[0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3. 3.]]


 A função zeros recebe como argumento um shape e inicializa uma matriz contendo valores zeros. A função ones retorna uma matriz com valores 1.

 A função full recebe dois argumentos, um shape e um valor, retornando uma matriz completa com o valor requerido no shape especificado



Agora refaça o exemplo utilizando NumPy.

In [ ]:
def gera_matriz(n_linhas, n_cols, k):
  A = np.ones((n_linhas,n_cols))
  A *= k
  return A

print (gera_matriz(4,3,5))

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
def gera_matriz(n_linhas, n_cols, k):
  A = np.full((n_linhas,n_cols),k)
  return A

print (gera_matriz(4,3,5))

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


Outros métodos importantes para matrizes em NumPy:

In [ ]:
print(np.arange(5))
print(np.arange(0, 2, 0.4))
print(np.linspace(0, 2, 5))


[0 1 2 3 4]
[0.  0.4 0.8 1.2 1.6]
[0.  0.5 1.  1.5 2. ]


Na linha 1, é utilizada a função arange. Quando passado um valor, ela retornará um array iniciando em 0 e usando como limite o valor passado (**note que ele não é incluído!**. No segundo caso, temos m valor inicial, um valor limitante e o passo a ser aplicado no vetor.

A função linspace recebe o valor inicial, o valor final (**incluído no vetor**) e o número de elementos.

De forma geral, usa-se arange com valores inteiros ou quando tiver um valor de passo específico. Já a linspace deve ser utilizada quando quiser incluir o valor final na sequência ou tiver um número fixo de elementos para produzir.

A indexação nos Arrays do Numpy funciona de forma similar ao slice de list.

In [ ]:
vetor = np.arange(10)
print(vetor[5])
print(vetor[5:])
print(vetor[:5])
print(vetor[2:8])
print(vetor[0:10:2])


5
[5 6 7 8 9]
[0 1 2 3 4]
[2 3 4 5 6 7]
[0 2 4 6 8]


Escreva uma matriz 3x3 e realize as operações descritas acima. **Lembre-se que a indexação em NumPy começa em 0**.

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matriz)
print()
print(matriz[1, 1])
print()
print(matriz[:, 1])
print()
print(matriz[0, :])
print()
print(matriz[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

5

[2 5 8]

[1 2 3]

[[2 3]
 [5 6]]


A partir de um array específico, é possível obter outros arrays de diferentes shapes, utilizando as funções ravel e reshape. Ravel "achata" o array, retornando um array novo com apenas uma dimensão. Reshape altera o formato da matriz para um shape especificado. Note que neste caso deve haver compatibilidade nos tamanhos.

In [ ]:
matriz_coluna = np.array([[1, 2], [3, 4], [5, 6]])
print(matriz_coluna)
print()
print(matriz_coluna.shape)
print()
vetor = matriz_coluna.ravel()
print(vetor)
print()
matriz_linha = matriz_coluna.reshape((2, 3))
print(matriz_linha)
matriz_invalida = matriz_coluna.reshape((2, 4))

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


ValueError: cannot reshape array of size 6 into shape (2,4)

No método reshape, deve-se prestar atenção para a ordem de redistribuição. Você consegue ver um método para esta redistribuição?

Veja que no erro foi tentado utilizar o reshape com um array de 6 elementos para se tornar um array de 8 elementos.


## Funções do NumPy

Algumas funções importantes em NumPy. Para iniciar, veremos o uso de uma matriz, que imagine sendo a quantidade de vendas de um item em cada mês por 10 anos.

In [ ]:
vendas_anos = np.array([[149, 499, 112, 430, 115, 390, 187, 316, 361, 483, 353, 400],
                        [258, 222, 461, 263, 384, 210, 452, 372, 417, 364, 468, 397],
                        [259, 329, 417, 132, 318, 256, 362, 496, 232, 132, 306, 174],
                        [117, 148, 480, 201, 160, 292, 146, 209, 298, 215, 358, 234],
                        [169, 229, 381, 119, 225, 270, 379, 272, 167, 332, 144, 359],
                        [358, 434, 228, 300, 122, 247, 142, 127, 191, 356, 450, 308],
                        [105, 251, 317, 147, 214, 280, 289, 338, 498, 133, 304, 225],
                        [156, 165, 299, 461, 290, 123, 451, 450, 353, 191, 167, 451],
                        [149, 377, 389, 176, 103, 439, 269, 132, 200, 391, 426, 175],
                        [137, 107, 229, 227, 198, 206, 432, 169, 323, 141, 155, 233]])
print(vendas_anos.shape)

(10, 12)


Veja o shape. Consegue entender estes valores?

Qual o número de vendas de fevereiro do segundo ano de histórico?

Encontre: a média de vendas de cada ano e a média de vendas por mês, usando a função mean do NumPy.

In [ ]:
print(np.mean(vendas_anos))
print(vendas_anos.mean())

275.7
275.7


A venda mensal de todos os anos e todos os meses é de 275,7.
Esta não é a resposta que precisamos.

Vamos fazer agora somente para o primeiro ano, passando o índice 0 como linha para a variável vendas_anos, depois você aprenderá como calcular para todos de uma vez só.

In [ ]:
primeiro_ano = vendas_anos[0, :]
print(primeiro_ano.mean())

316.25



O parâmetro axis representa o eixo no qual você quer fazer a operação.

Como a variável primeiro_ano é um vetor unidimensional, somente possui um eixo:

In [ ]:
print(primeiro_ano.mean(axis=0))

316.25


O resultado continua sendo 316,25.
Utilizando axys, resolva a pergunta requerida.

In [ ]:
media_ano = vendas_anos.mean(axis=1)
print(media_ano)
print(media_ano.shape)


[316.25       355.66666667 284.41666667 238.16666667 253.83333333
 271.91666667 258.41666667 296.41666667 268.83333333 213.08333333]
(10,)


In [ ]:
media_meses = vendas_anos.mean(axis=0)
print(media_meses)
print(media_meses.shape)


[185.7 276.1 331.3 245.6 212.9 271.3 310.9 288.1 304.  273.8 313.1 295.6]
(12,)


O shape da variável media_meses é igual a 12, que é o número de meses no ano. Isso é outro indicativo de que você fez a operação no eixo correto.


In [ ]:
soma_ano = vendas_anos.sum(axis=1)
print(soma_ano.shape)
print(soma_ano)
print()
maximo_vendas_anuais = soma_ano.max()
print(maximo_vendas_anuais)


(10,)
[3795 4268 3413 2858 3046 3263 3101 3557 3226 2557]

4268


In [ ]:
print(vendas_anos.max())
print(vendas_anos.max(axis=0))
print(vendas_anos.max(axis=1))


499
[358 499 480 461 384 439 452 496 498 483 468 451]
[499 468 496 480 381 450 498 461 439 432]


Perceba que o método sem argumentos calculou o maior valor de toda a matriz vendas_anos. Com o parâmetro axis=0, é obtido o maior valor de vendas para cada mês em todos os anos, por isso o vetor tem 12 elementos. E para o valor de axis igual a 1, é calculado o máximo de vendas de cada ano, tendo assim um vetor com 10 valores.

Agora, qual foi o ano que obteve a maior venda? É fácil inspecionar o vetor de 10 elementos e dizer que foi a primeira posição, mas e se o vetor tivesse 100 elementos? 1.000? Ou até mesmo 10.000?

Caso você tenha um array e queira encontrar a posição que contém o maior valor, você utilizará a função argmax. Esta função retorna um índice e pode ser usado para acessar o array original. Confira o exemplo a seguir.


In [ ]:
indice_max = soma_ano.argmax()
print(indice_max)
print(soma_ano[indice_max])

1
4268
